name: notebooklm-rag
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - langchain
    - langchain-google-genai
    - langchain-community
    - langchain-text-splitters
    - langchain-core
    - chromadb
    - pypdf
    - streamlit
    - python-dotenv
    - watchdogs

